name: campgrounds
region: sfo
workers:
- image:
    registry: hjhart
    registry_type: DOCKER_HUB
    repository: vaccine
    tag: latest
  instance_count: 1
  instance_size_slug: professional-m
  name: campgrounds
  source_dir: /